version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: flix-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: flix-api
      POSTGRES_PASSWORD: flix-api

volumes:
  postgres-data: