# Generated by Django 4.2.7 on 2023-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='resume',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
