# Generated by Django 4.2.7 on 2023-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
